version: '3'
services: 
   db: 
      # mdillon's image comes with postgis pre-installed
      image: mdillon/postgis
      container_name: pandemix-db
      restart: always
      environment:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_NAME: pandemix
      ports: 
        - 25060:5432
      volumes:
        - /data/postgres/pandemix:/var/lib/postgresql/data